apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quantum

resources:
- deployment.yaml
- service.yaml

images:
- name: quantum-app
  newName: klimentchakarovski/quantum-app
  newTag: fae8e728f660fe02fba26dc97de060916364c810

commonLabels:
  app: quantum-app
