apiVersion: v1
kind: Service
metadata:
  name: quantum-app-service
  labels:
    app: quantum-app
spec:
  type: ClusterIP
  selector:
    app: quantum-app
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
