apiVersion: v1
kind: Service
metadata:
  name: quantum-app-service
  labels:
    app: quantum-app
spec:
  type: NodePort
  selector:
    app: quantum-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050
      protocol: TCP
