name: Quantum DevOps CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install black flake8
      - name: Check formatting with Black
        run: black --check .
      - name: Run Flake8
        run: flake8 .

  unit-test:
    name: Run Unit Tests (including parameterized quantum simulations)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage matplotlib qiskit qiskit-aer numpy
      - name: Run tests with coverage
        run: |
          export PYTHONWARNINGS="ignore::DeprecationWarning"
          coverage run -m pytest -v
          coverage xml -o coverage.xml
      - name: Display coverage
        run: cat coverage.xml

  docker-build-test:
    name: Docker Build, Test & Scan
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t quantum-app:test .
      - name: Run unit tests inside Docker
        run: docker run --rm quantum-app:test pytest -v
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: quantum-app:test
