name: Lint and Test Quantum Simulator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pytest coverage

      # Step 4: Run Black (code formatting check)
      - name: Run Black
        run: black --check .

      # Step 5: Run Flake8 (lint)
      - name: Run Flake8
        run: flake8 .

      # Step 6: Run unit tests with coverage and suppress warnings
      - name: Run unit tests
        run: |
          export PYTHONWARNINGS="ignore::DeprecationWarning"
          coverage run -m pytest -v
          coverage xml -o coverage.xml

      # Step 7: Display coverage report
      - name: Display coverage
        run: cat coverage.xml
