name: Lint and Test Quantum Simulator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Run Black
        run: black --check .

      - name: Run Flake8
        run: flake8 .

  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest

      - name: Run unit tests with coverage
        run: |
          export PYTHONWARNINGS="ignore::DeprecationWarning"
          coverage run -m pytest -v
          coverage xml -o coverage.xml

      - name: Display coverage
        run: cat coverage.xml
